export const THEME = {
    LIGHTBLUEBACKGR_COLOR: '#93d3fb',
    LIGHTBLUE_COLOR: 'skyblue',
    BUTTONBLUE_COLOR: '#6376b0',
    BUTTONFADE_COLOR_1: '#87ceeb',
    BUTTONFADE_COLOR_2: '#9bc4e2',
    BUTTONFADE_COLOR_3: '#5889ad',
    BACKGROUNDFADE_COLOR_1: '#95d3f8',
    BACKGROUNDFADE_COLOR_2: '#e5f4fd',
    BACKGROUNDFADE_COLOR_3: '#f2fafe',
}